### ISSUE TITLE
[lint] fix flake8 warnings and don't ignore them

### ISSUE THREAD

**Issue by PiRK** [Bitcoin-ABC/ElectrumABC#252]
This is a list of flake8 error flags that are currently not enforced, but should be.

Easy to fix:

- [x] E262 inline comment should start with ‘# ‘. Done in #255 
- [x] E265 block comment should start with ‘# ‘. Done in #255 
- [x] E266 too many leading ‘#’ for block comment
- [x] E731 do not assign a lambda expression, use a def
- [x] E741 do not use variables named ‘l’, ‘O’, or ‘I’

Less easy:
- [x] E501 _line too long (> 88 characters)_: investigate what black allows to fix. Sometimes related to #248?
- [x] E402 _module level import not at top of file_ (sometimes there is a good reason, such as working around a circular dependency). Done in #255 
- [x] E722 _do not use bare except, specify exception instead_ (requires finding which specific errors are reasonable to catch in each situation)

See:
-  https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
-  https://flake8.pycqa.org/en/latest/user/error-codes.html

**Comment by PiRK** [comment]
E722 cannot be done properly in a reasonable amount of time, so I only did the basic `except:` -> `except Exception:` fix for now.
